in-toto/go-witness

.github/workflows/golangci-lint.yml, .github/workflows/release.yml, .github/workflows/verify-licence.yml, .goreleaser.yaml, dsse/dsse.go, dsse/dsse_test.go, policy/policy_test.go
Adds the ability to require at least a specified number of verifiers to
successfully verify a DSSE envelope.
Also fixes witness issue #194 where multiple public keys within a policy
will cause all verification to fail. This was due to the DSSE verify
function returning as soon as a single verifier fails. Now the code
appropriately tries to verify against all passed in verifiers and only
throws an error if no verifier successfully verifies the envelope or the
threshold is unmet.
Signed-off-by: Mikhail Swift <mikhail@testifysec.com>
=> feat: add dsse verifier threshold

attestation/oci/oci.go
I was not able to reproduce this locally for some reason but had to set up a CI job in GitLab
Here is an example of the error:
[https://gitlab.com/testifysec/judge-platform/web/-/jobs/2994900989](https://gitlab.com/testifysec/judge-platform/web/-/jobs/2994900989)
Here is an example with the fix:
[https://gitlab.com/testifysec/judge-platform/web/-/jobs/2994887589](https://gitlab.com/testifysec/judge-platform/web/-/jobs/2994887589)
This is the binary I downloaded in the pipeline
https://github.com/testifysec/witness/releases/download/v0.0.7-test-ci/witness
=> fix: don't return error on EOF, break instead.

attestation/aws-iid/aws-iid.go, attestation/oci/oci.go, attestation/sarif/sarif.go, attestation/scorecard/scorecard.go, rekor/rekor.go, rekor/rekor_test.go
Signed-off-by: Mikhail Swift <mikhail@testifysec.com>
=> chore: remove fmt.Print functions in favor of log library

attestation/file/file.go, attestation/file/file_test.go
Detects if we get an ErrNotFound from filepath.EvalSymlinks and if so bails out from walking that part of the filesystem tree.
Signed-off-by: Mikhail Swift <mikhail@testifysec.com>
=> bug: gracefully handle broken symlinks

cryptoutil/util.go, dsse/dsse.go, dsse/dsse_test.go, dsse/sign.go, dsse/verify.go, go.mod, go.sum, policy/policy.go, run.go, sign.go, source/verified.go, timestamp/tsp.go, timestamp/tsp_test.go, verify.go
* Adds an array to the signatures on a dsse envelope representing
timestamps of that signature
* Adds implementation of RFC3161 timestamps for signing and policy
enforcement
* Adds policy support for ensuring signatures have timestamps from a
trusted time stamp authority
=> RFC 3161 Timestamping Support

attestation/oci/oci.go, attestation/product/product.go, attestation/product/product_test.go
This fixes the EOF error and some additional issues relating to small files discovered when I created some tests.
I added support for detecting pdf files to show the pattern which can be used when adding additional type detection.
=> fix: fixes bug where files under 512 bytes would cause EOF error

README.md, attestation/aws-iid/aws-iid.go, attestation/commandrun/commandrun.go, attestation/context.go, attestation/environment/environment.go, attestation/factory.go, attestation/factory_test.go, attestation/gcp-iit/gcp-iit.go, attestation/git/git.go, attestation/github/github.go, attestation/gitlab/gitlab.go, attestation/jwt/jwt.go, attestation/material/material.go, attestation/maven/maven.go, attestation/oci/oci.go, attestation/oci/oci_test.go, attestation/product/product.go, attestation/sarif/sarif.go, policy/policy_test.go, run.go
This adds the ability for attestors to expose available configuration
options including their names, descriptions, and a function that can be
used to set the configuration option on the instantiated attestor.
This will let users of the registry to expose options to the end user,
such as through CLI flags in the case of Witness CLI
=> feat: attestor config options

attestation/product/product.go, attestation/product/product_test.go, go.mod, go.sum
This allows users to configure the product attestor to only include certain files from the product attestor as subjects to the attestation.
=> feat: add include and exclude glob options to product attestor

attestation/aws-iid/aws-iid.go, attestation/aws-iid/aws-iid_test.go, attestation/gcp-iit/gcp-iit.go, attestation/git/git.go, attestation/github/github.go, attestation/gitlab/gitlab.go, attestation/maven/maven.go, attestation/oci/oci.go
We encountered errors with `witness verify` failing unexpectedly despite having the appropriate attestations available. The issue laid with some backrefs not being able to be calculated appropriately, which the policy engine then was unable to build the graph of attestations to satisfy the policy.
The root cause of the issue wound up being that in some attestors subjects were calculated in the `Attest` function and stored for later use in the `Subjects` function. However, this causes issues when we are reading attestations from a source and in a context where `Attest` would have never been run on the attestor being inspected.
The solution I implemented is to calculate subjects (and by extenstion backrefs) on demand from the unexported fields on the attestor structs. This way when we …
=> fix: calculate subjects on demand always

.github/workflows/release.yml
Updates to a newer version of the witness-run-action with the updated fulcio url as well as updates our tests to use the new fulcio url.
=> fix: update github actions to use new fulcio url

attestation/git/git.go, attestation/git/git_test.go
Fixes https://github.com/testifysec/witness/issues/275
When witness runs on an empty git repo without commits, it shouldn't error with `reference not found` 
1. start a new git repo, do not make any commits
2. run witness on it
3. observe witness fail
- witness doesn't fail on step 3
=> fix(witness): witness should not error on an empty git repo with no commits

attestation/aws-iid/aws-iid.go, attestation/commandrun/tracing_linux.go, attestation/context.go, attestation/factory.go, attestation/gcp-iit/gcp-iit.go, attestation/github/github.go, attestation/gitlab/gitlab.go, attestation/maven/maven.go, attestation/oci/oci.go, attestation/sarif/sarif.go, log/log.go, policy/policy.go, signer/file/file.go, source/verified.go, verify.go
Continuation of https://github.com/in-toto/go-witness/pull/83.
The main change needing reviewed here is the changes to [log.go](https://github.com/in-toto/go-witness/pull/85/files#diff-894630a7ed925c7768a861c4465bc9ad393f7937df7cac5c77ab123c03921aeeL50-L52). This checks in the relevant f functions (e.g., Debugf, Warnf) for arguments of type error, and handles that inside the wrapper function.
=> Refactoring error messages to use %w formatting directive and fix logging issue

log/log.go
I introduced a bug as I was not returning and otherwise logging as usual if an error wasn't found. This PR fixes that. See https://github.com/in-toto/go-witness/pull/85 for introduction of the original issue.
=> Fixing bug introduced in logs - warning and debug logs not printing

.github/workflows/release.yml, .github/workflows/verify-licence.yml, .github/workflows/witness.yml, DEPENDENCY.md, SECURITY-INSIGHTS.yml
=> Update SECURITY-INSIGHTS.yml with additional information

attestation/factory.go
allows a single attestor to be added rather than multiple as input to function. See https://github.com/in-toto/go-witness/pull/104 for more details.
=> Adding function to add a single attestor

attestation/maven/maven.go, attestation/maven/maven_test.go
Reopened version of https://github.com/in-toto/go-witness/pull/100.
=> Adding support for supplying POM on Maven Attestor

dsse/dsse.go, dsse/dsse_test.go, dsse/verify.go, verify.go
After discovering that the `policy-ca` flag in `github.com/in-toto/witness` was not wired up correctly, I noticed that some change was required in go-witness to feed it into the verification function for the policy DSSE envelope. I also noticed that there was no way of specifying a timestamp authority CA certificate for the policy. Given that `Sign` supports specifying said timestamp authority, it seemed clear that adding support in Verify would be worthwhile.
Note that currently, the way that we are verifying the policy is different from how we verify attestations. It seems that said disparity does not need to be there and I will therefore create another Issue to track the need to refactor this. 
See Github issue here: https://github.com/in-toto/go-witness/issues/125
=> Adding support for using timestamp authority and CA certificates for verifying policy

dsse/dsse_test.go, dsse/sign.go, dsse/verify.go, run.go, timestamp/fake.go, timestamp/timestamp.go, verify.go
This might not be an improvement we want to accept but it felt worthwhile moving the Timestamper interface(s) and the fake timestamper for testing to the `timestamp` package.
This is a bit of a "take or leave" PR, so happy for it to be closed if we don't feel it as necessary / optimal.
=> Moving the timestamper interfaces to the timestamp directory

attestation/aws-iid/aws-iid.go, attestation/commandrun/tracing_linux.go, attestation/context.go, attestation/file/file.go, attestation/file/file_test.go, attestation/gcp-iit/gcp-iit.go, attestation/git/git.go, attestation/github/github.go, attestation/gitlab/gitlab.go, attestation/maven/maven.go, attestation/oci/oci.go, attestation/oci/oci_test.go, attestation/product/product_test.go, cryptoutil/digestset.go, cryptoutil/gitoid.go
When the functionality to calculate gitoids was added, there was a bit of tech debt incurred since they didn't implement hash.Hash. This remedies this with an admitedly hacky implementation of hash.Hash that wraps the gitoid code. This also standardizes our cryptoutil fucntions around the DigestValue struct that was added around this time to differentiate between gitoids and regular hash functions.
=> refactor: move gitoid code to cyrptoutil, use digestvalue everywhere

.github/workflows/release.yml
The release action introduced in a previous PR is broken due to a small typo. This fixes it.
=> fixing error in github actions workflow

.github/workflows/golangci-lint.yml
For reasons that I can't quite pinpoint, https://github.com/in-toto/go-witness/pull/131's golangci-lint workflow is failing repeatedly.
I am unable to reproduce this locally, but it is clear that [this issue is occurring elsewhere](https://github.com/golangci/golangci-lint-action/issues/244), with projects such as [https://github.com/prometheus-operator/prometheus-operator/pull/6221](prometheus-operator) and [https://github.com/kumahq/kuma/pull/8820](kuma) opting to add the workaround in this PR. This seems like the correct change to minimise time lost investigating this issue.
It doesn't seem like there will be a lot of time lost in the workflows by skipping pkg cache, and if approved i'll also add a PR in https://github.com/in-toto/witness and https://github.com/in-toto/archivista to …
=> Adding workaround due to failing workflows

internal/test/util.go, policy/constraints.go, policy/policy.go, policy/step.go, verify.go, verify_test.go
This PR makes it possible to inspect the certificate attached to the signature (in the case that it was signed with x509 certificate) against user supplied cert constraints.
It should be noted that the constraint checks we perform is against *any* verifier that passes the initial policy verification logic. I am not sure whether this is an issue, but it is still something to be aware of. see [here](https://github.com/in-toto/go-witness/compare/main...ChaosInTheCRD:checking-policy-against-cert-constraints?expand=1#diff-32870c78c32d49e31ad4f22eaeac957ae6b988eea6fc937c9dba68035ac0d1b6R202-R212).
Another thing to note is that currently this logic has been broken out into a `verifyPolicySignature` function underneath the main `Verify` function. There may be a good place in the library to put …
=> Checking policy signature against cert constraints

signer/vault/request.go
A user encountered an issue while using witness with the vault pki signer.
```
msg="failed to create vault signer: failed to issue certificate: json: cannot unmarshal array into Go struct field issueResponse.warnings of type string"
level=error msg="failed to load signers"
```
It turns out warnings is intended to be an array of strings, as indicated by hashicorp's own client lib: 
https://github.com/hashicorp/vault-client-go/blob/cfdcbeda2e34770a045cc9f71ad25db195e97181/response.go#L31
However, their documentation seems inaccurate and represents this as a string:
https://developer.hashicorp.com/vault/api-docs/secret/pki#sample-response-6
Confirmed that this change fixes the user's error.
=> fix: vault warnings are an array, not a string

imports.go, policy/policy.go, policy/policy_test.go
Ran into an issue testing a policy with multiple public key functionaries. I would continually get ErrKeyIDMismatch when loading the second key. Turns out the verifier variable was being persisted on each iteration and failing the nil check to reload the new verifier. Resetting this within the for loop fixes it.
=> fix: reset verifier each iteration while loading pub keys from policy

internal/policy/policy.go, policy/constraints.go, run.go, verify.go
These changes are necessary to fully enable https://github.com/in-toto/witness/pull/353 to work. Also note that this PR contains a fix for a panic in the case of a `[]RunResult` of length 0 (implying an error) getting returned from `Run`.
=> Allow certificate inspection on policy signature verification (including fulcio extensions)

dsse/dsse.go, dsse/verify.go
As the description says, we want the verifier back so we can present the verifier ID that introduced the error.
=> BUG: `verifyX509Time` should return the verifier even if the verify fails (we want to get information about it later)

.github/workflows/release.yml
it seems like the releaser action needs write permissions? Seen in the documentation [here](https://github.com/softprops/action-gh-release?tab=readme-ov-file#permissions)
=> Fix releaser permissions

policy/policy.go, policy/step.go
If any evidence exists that causes a step evaluation to fail, the entire policy will fail, even if there's passing evidence at another search depth. Also, results from the verifyArtifacts function are carrying forward passed results, even if the artifact comparison doesn't match.
=> Step analyze fix

attestation/context.go
Allowing per attestor type to run all the attestors in parallel to speed up the process.
=> Parallel attestors per type

attestation/factory.go, attestation/sbom/sbom.go
This will allow the SBOM attestor, and future attestors, to support multiple types for a single attestor. In the case of the SBOM attestor, we'd like to record the appropriate type for SPDX, CycloneDX, etc without having to implement a different attestor for the same functionality.
=> Allow attestors to have multiple types

attestation/omnitrail/omnitrail.go, imports.go, imports_nonwindows.go
Currently omnitrail expects a POSIX filesystem, which windows does not supply. This causes windows builds to break when compiled with the omnitrail attestor. This PR adds a build flag to skip the omnitrail attestor when building for windows.
Description
(optional, using `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when the PR gets merged)*
Fixes #
=> fix: disable omnitrail attestor on windows

attestation/commandrun/commandrun.go, attestation/commandrun/tracing_linux.go, attestation/file/file.go, attestation/file/file_test.go, attestation/material/material.go, attestation/product/product.go
- When ptracing programs, restrict the product attestor to only attest for files recorded as "opened" by the commandrun attestor. Then, files created by a separate process running concurrently will not be mistakenly included in the attestation products (this happens currently).
- Keep track of newly created files when tracing with ptrace. Previously, they would not be added to the `OpenedFiles` list because the file would not exist when attempting to calculate its digest.
=> better concurrency support on Linux

policy/policy.go, policy/step.go, source/memory.go
This PR closes #316 where repeated verification lines existed that looked repeated. It also fixes log lines incorrectly reporting that certain attestations weren't seen. It does so by:
- removing some unnecessary functionality that was duplicating the job of checking for the presence of certain attestations in the collection
- not continuing through the verification flow if no collection was found from a search
- preventing the memory source repeating the search process more than once. memory (attestation files) is a flat data structure so there is only a need to search once.
#316
This PR will be supplemented by a small PR (update: https://github.com/in-toto/witness/pull/485) in https://github.com/in-toto/witness. While it is possible to test this without that branch, some of the reported …
=> fix: repetitive and incorrect log lines on `witness verify`

attestation/product/product.go, attestation/sbom/sbom.go
The current CycloneDX and SPDX checks are too naive, meaning some generated SBOMs will not be correctly detected as SBOMs. This will introduce a more lenient check for identifying information which indicates the format of the SBOM without overly sacrificing performance.
The check will see if a file's first 500 characters contains identifying information related to the type of SBOM the file might be, rather than the naive HasPrefix check.
=> improve SPDX and CycloneDX JSON SBOM format detection

.github/workflows/golangci-lint.yml, attestation/policyverify/policyverify.go, policy/policy.go, policy/policy_test.go, signer/kms/aws/client.go, verify.go
this closes https://github.com/in-toto/witness/issues/427
=> fix: Passing kms provider options down to initialisation of functionaries

Makefile, dsse/verify.go
Added the fix and introduced `make lint` for local tests.
```
dsse/verify.go:98:6: S1009: should omit nil check; len() for []byte is defined as zero (gosimple)
if sig.Certificate != nil && len(sig.Certificate) > 0 {
^
```
=> fix: golangci-lint failing due nil check

attestation/jenkins/jenkins.go, attestation/jenkins/jenkins_test.go, attestation/slsa/slsa.go, attestation/slsa/slsa_test.go, imports.go, internal/attestors/jenkins.go, schemagen/jenkins.json
Add a Jenkins build attestor. We can use it in the SLSA provenance data as well, which currently only supports Github Actions and Gitlab CI.
This will allow us to capture data related to a Jenkins build without having to capture the entire scope of environment variables (in case there is sensitive data in the environment).
Closes #315 
=> add jenkins attestor

attestation/context.go, attestation/file/file.go, attestation/file/file_test.go, attestation/link/link_test.go, attestation/material/material.go, attestation/product/product.go, cryptoutil/digestset.go, cryptoutil/dirhash.go
Related to: https://github.com/in-toto/witness/pull/436
This a different approach to #65. It captures a dirhash for material and product if the dir is mentioned as an argument.
```
witness run --dirhash-glob node_modules/* --step build -- npm clean-install
```
The argument can be repeated multiple time and globs with `**` are not allowed.
The output will generate a dirhash based on the algorithm use by golang in https://pkg.go.dev/golang.org/x/mod/sumdb/dirhash and is the same as described in the in-toto digest spec ([here](https://github.com/in-toto/attestation/blob/main/spec/v1/digest_set.md#dirhash))
The subject for a dirhash will be `https://witness.dev/attestations/product/v0.1/dir:node_modules/example/`.
The policy works correctly and also `artifactsFrom` are correctly checked.
=> Adding functionality for dirhash in library

verify_test.go
This adds an additional test for policy verification to make sure that policy verification fails if all the expected attestations do not appear in a step's collection.
This will help prevent breakages as changes to the internal policy code occur. The current tests are an improvement over what we had, but they will definitely need improvement over time. These serve as a baseline to increase confidence when modifying policy code.
(optional, using `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when the PR gets merged)*
Fixes #
=> test: add additional policy verification test

attestation/git/git.go, attestation/git/git_bin.go, schemagen/git.json
By using the native git client its possible to improve the speed significantly.
The default approach is using go-git to no rely on a git client that is installed. But if git is found it will use the git client instead which is much faster compared to the go-git library.
Fixes https://github.com/in-toto/go-witness/issues/358
I have large mono repo. For posterity here are the results of a simple run that does not change anything and then with the changes. Basically: `witness run --step build -- echo "hello"`
Repository stats of the working tree.
```shell
$ git count-objects -vH
count: 219
size: 1.13 MiB
in-pack: 2468342
packs: 29
size-pack: 1.36 GiB
prune-packable: 25
garbage: 0
size-garbage: 0 bytes
```
v0.6.0: 82.82s user 96.35s system 63% cpu 4:40.58 …
=> chore: Improve the git status speed.

signer/fulcio/fulcio.go
Description
Fixes https://github.com/in-toto/witness/issues/535
=> bug(fulcio): Fixes Witness #535

attestation/file/file_test.go, cryptoutil/dirhash.go
Description
Handle the case where the dirHash option is used and the dirHash matched folders contain symlinks.
Fixes #442.
=> fix: --dirhash-glob fails with symlinked directories (#442)

attestation/commandrun/commandrun.go, attestation/context.go
Allow customizing destination of `go-witness` output. This is useful for storing logs and better integrating the library into systems without `stdout` capabilities.
=> Add ability to control command run process outputs

attestation/context.go, attestation/docker/docker.go, attestation/docker/docker_test.go, attestation/gitlab/gitlab.go, internal/docker/metadata.go, run.go, schemagen/docker.json
Description
This PR introduces:
- a run option to allow for errors to be ignored
- a refactor of the docker attestor to allow the metadata of multiple container images to be stored in the predicate
- some minor bug fixes found after merge of the attestor
- a minor fix in the way we are parsing the architecture from the material URI in the docker metadata file.
=> Docker attestor refactor

attestation/k8smanifest/k8s.go, schemagen/k8smanifest.json
This PR adds to the k8smanifest attestor to parse node manifests and store information about each node in the predicate
=> chore: added the ability to attest node information

signer/fulcio/fulcio.go
By default we generate an elliptic P384 for our fulcio signer. When we get the proof of possession challenge from fulcio, we were hashing it with SHA256 during the signing process. This was working fine until recently, when we started getting failures while getting certificates from Fulcio.
This seems to trace back to this commit:
https://github.com/sigstore/sigstore/commit/63abeebb6c891fb583a556210cb6d593a95e688b
This adds a registry to map the type of public key and which algorithms to use by default. This expects SHA384 to be used in our case.
Swapping the signer to use SHA384 when signing the challenge fixes our error.
(optional, using `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when the PR gets merged)*
Fixes #
**Special notes for your …
=> fix: use sha384 for signing proof of possession challenge from fulcio

schemagen/schema.go
This PR updates the schema generation tool to only write schema files when their content has actually changed.
- Added content comparison before writing schema files
- Skip writing if the new content matches existing file content
- Log when schemas are up to date vs when they need updating
- Reduces unnecessary file updates
- Prevents git noise from unchanged schemas
- Avoids updating file timestamps when content hasn't changed
- Makes it easier to see actual schema changes in version control
Run `go run ./schemagen` multiple times and observe that unchanged schemas are skipped:
```
2025/05/23 15:43:48 Schema for attestor environment is up to date, skipping
2025/05/23 15:43:48 Schema for attestor material is up to date, skipping
2025/05/23 15:43:48 Writing schema for attestor …
```
=> feat(schemagen): only update schema files when content changes

run.go
Instead of generic error messages, each attestor error now includes the specific attestor name that failed
Description
When the witness CLI logs log.Debugf("attestor execution failed: %v", err), it will now show messages like "attestor git failed: repository does not exist" instead of just "repository does not exist"
=> log failed attestor name for better debugging
